name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: compile test
      run: g++ -o test.exe test.cpp
    - name: run tests
      run: ./test.exe
